# Site settings
name: Mendix
description: ""
url: "https://docs.mendix.com"
baseurl: ""
encoding: utf-8

# Base variables
latest_major_version: "6"

timezone: Netherlands/Amsterdam
permalink: ordinal

####################################
######        ALGOLIA        #######
####################################

algolia:
  application_id:    'OHBX5T982M'
  index_name:        'documentation'
  read_only_api_key: 'd23e5ac47b71a0f51afa5fedc695b718'
  excluded_files:
    - index.html
    - howto6/index.html
    - refguide6/index.html

####################################
######        SPACES         #######
####################################
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: mxdefault

  # VERSION SPECIFIC CONTENT
  - scope:
      path: 'howto6'
      type: pages
    values:
      space: "Mendix 6 How-to's"
      menus:
        - "howto6"
        - "tips"
        - "bestpractices"
        - "appstore"
        - "mendixcloud"
  - scope:
      path: 'refguide6'
      type: pages
    values:
      space: "Reference Guide 6"
      menus:
        - "refguide6"
        - "community"

  # VERSION INDEPENDENT
  - scope:
      path: 'community'
      type: pages
    values:
      space: "Community"
      menus:
        - "refguide6"
        - "community"
  - scope:
      path: 'apidocs'
      type: pages
    values:
      space: "API documentation"
      menus:
        - "apidocs"
  - scope:
      path: 'ATS'
      type: pages
    values:
      space: "ATS (Application Test Suite)"
      menus:
        - "ATS"
  - scope:
      path: 'APM'
      type: pages
    values:
      space: "Application Performance Monitor"
      menus:
        - "APM"
  - scope:
      path: 'MXSDK'
      type: pages
    values:
      space: "Mendix Platform SDK"
      menus:
        - "MXSDK"
  - scope:
      path: 'mxsupport'
      type: pages
    values:
      space: "Mendix Support"
      menus:
        - "mxsupport"
  - scope:
      path: 'tips'
      type: pages
    values:
      space: "Tips and Tricks"
      menus:
        - "howto6"
        - "tips"
        - "bestpractices"
        - "appstore"
        - "mendixcloud"
  - scope:
      path: 'bestpractices'
      type: pages
    values:
      space: "Best Practices"
      menus:
        - "howto6"
        - "tips"
        - "bestpractices"
        - "appstore"
        - "mendixcloud"
  - scope:
      path: 'appstore'
      type: pages
    values:
      space: "App Store"
      menus:
        - "howto6"
        - "tips"
        - "bestpractices"
        - "appstore"
        - "mendixcloud"
  - scope:
      path: 'mendixcloud'
      type: pages
    values:
      space: "Mendix Cloud"
      menus:
        - "howto6"
        - "tips"
        - "bestpractices"
        - "appstore"
        - "mendixcloud"

####################################

exclude:
  - Gemfile
  - Gemfile.lock
  - Gemfile.lock.osx
  - Gemfile.lock.win
  - README.md
  - Rakefile
  - node_modules
  - vendor
  - package.json
  - test.txt
  - run.bat

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  style: :expanded

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - algoliasearch-jekyll
